### ISSUE TITLE
Login boucle sur login

### ISSUE THREAD

**Issue by boscorelly** [romnvll/Open-Centreon-Discovery#10]
bonjour,

j'ai suivi le guide d'éric pour l'installation.

par contre, quand je suis sur la page de login, que je rentre n'importe quel login, il boucle sur la page de login sans aucun message d'erreur.

une idée ?

centreon 21.10

**Comment by romnvll** [comment]
Bonjour Camille.
Tu es sur la centos de centreon ?
Est-ce que tu as mis le login/MDP de centreon dans le fichier de
configuration ?

Le jeu. 21 avr. 2022 à 18:02, Camille Ollié ***@***.***> a
écrit :

**Comment by boscorelly** [comment]
tout à fait.

centos à jour, et j'ai bien mis les infos dans le fichier de conf. J'ai créé un user expres pour ça, avec les droits sur l'api (j'ai meme mit le compte admin pour tester)

**Comment by romnvll** [comment]
Il me semble que les mots de passe avec des caractères genre , ou ; ça
passe pas ...

Le jeu. 21 avr. 2022 à 18:08, Camille Ollié ***@***.***> a
écrit :

**Comment by boscorelly** [comment]
il n'y a que des caractères alphanumériques, j'ai utilisé le générateur de centreon ^^

**Comment by boscorelly** [comment]
si je mets un mauvais mot de passe dans la config pour l'user de l'api > ça m'envoie bouler avec l'erreur définie dans verif.php

pour tous les autres cas (mauvais user, mauvais pass, ou les 2), retour en arrière, et pas de message d'erreur alors que je devrais etre sur index.php?login=false

**Comment by romnvll** [comment]
A froid comme ça je n'ai pas d'idée.
J'ai des disponibilités lundi, est-ce qu'on peut voir ça lundi en remote ?

Le jeu. 21 avr. 2022 à 18:26, Camille Ollié ***@***.***> a
écrit :

**Comment by boscorelly** [comment]
j'ai modifié verif.php pour renvoyer sur indexe.php en cas d'erreur de login. dans tous les cas là, il me renvoie vers cette page.

donc `($_POST['login'] === $config['centreon']['user']) && ($_POST['password'] === $config['centreon']['password'])`ne marche pas.

php -v
PHP 8.0.17

**Comment by boscorelly** [comment]
bon, après revérif dans tous les sens, ça a marché. Pour une raison que j'ignore, ça n'avait pas marché avec les anciens credential de l'user que j'ai créé pour le discover, et là ça a marché.
du coup je testais avec mon compte centreon perso et ça marchait pas.
par contre il ne prompte rien du tout dans ce cas.

**Comment by romnvll** [comment]
Il ne prompt rien ?
Ça veut dire quoi ?

Le jeu. 21 avr. 2022 à 18:38, Camille Ollié ***@***.***> a
écrit :

**Comment by boscorelly** [comment]
Il n’affiche rien. Tu as mis un écho qui ne s’affiche jamais  De : romnvll ***@***.***>Envoyé : jeudi, avril 21, 2022 6:42 PMÀ : romnvll/Open-Centreon-Discovery ***@***.***>Cc : Camille Ollié ***@***.***>; State change ***@***.***>Objet : Re: [romnvll/Open-Centreon-Discovery] Login boucle sur login (Issue #10) 

Il ne prompt rien ?

Ça veut dire quoi ?



Le jeu. 21 avr. 2022 à 18:38, Camille Ollié ***@***.***> a

écrit :

**Comment by romnvll** [comment]
Bonjour Camille,
mauvais mot de passe vers centreon ?
il me semble aussi que si il y a un caractère spécial genre un "@" ça peut
provoquer cette situation.

Le mar. 11 oct. 2022 à 09:56, Camille Ollié ***@***.***> a
écrit :

**Comment by boscorelly** [comment]
Bonjour,

navré pour mon silence.

j'ai quitté la société où j'étais en train de mettre ça en place, du coup je n'utilise plus ce projet :(

Merci quand même !
