### ISSUE TITLE
Authentification failed

### ISSUE THREAD

**Issue by JonioDiPonio** [romnvll/Open-Centreon-Discovery#12]
Bonjour,

J'ai un soucis avec le module de discovery, le login et mdp sont corrects (identiques à ceux de centreon) mais quand je fais un discovery sur une plage IP mes machines remontent mais je ne peux pas choisir de template ou le poller. 
![image](https://github.com/romnvll/Open-Centreon-Discovery/assets/71132109/b3ce693c-93dc-4de5-83b4-ca3e4cb4d49a)
Je suis sur une debian 11 avec la dernière version de centreon 23.04.

Sur une machine de test sous centOS avec la version 22.10 de centreon je n'avais pas de soucis pour le discovery et les templates mais sous debian les dir sont différents donc je ne serais pas surpris d'avoir mis un fichier (le php surtout) au mauvais endroit ce qui empeche la connexion ou alors comme j'ai pu voir sur un autre problèmes; les caractères spéciaux mais je ne peux pas les enlever comme ils sont obligatoire en version 23.04 maintenant pour le mot de passe admin de centreon.

**Comment by JonioDiPonio** [comment]
Edit : j'ai désactivé l'option des caractères spéciaux pour le mot de passe dans centreon et ca fonctionne parfaitement au final

**Comment by romnvll** [comment]
Bonjour,
Je viens de découvrir vos messages.
Je vais essayer de regarder, quand j'aurai un peu de temps le problème des
caractères spéciaux dans les mots de passe.
Merci pour votre retour.
