### ISSUE TITLE
[proxy_fcgi:error] [pid 23269] (70007)The timeout specified has expired:

### ISSUE THREAD

**Issue by aSysadminStory** [romnvll/Open-Centreon-Discovery#3]
Salut,

- ISO Centreon open source
- Version 20.04.07
- CentOS 7

J'ai eu un timeout lors du premier test. 

```
[Wed Dec 09 10:30:29.316315 2020] [proxy_fcgi:error] [pid 23934] (70007)The timeout specified has expired: 
[client xx.xx.xx.xx:12632] AH01075: Error dispatching request to : (polling), referer: http://xxxxxxxxxxx/discovery/
```
J'ai modifié la conf httpd24 en rajoutant la valeur timeout et ça fonctionne désormais, j'ai bien la liste des hosts.

timeout=1800
ProxyTimeout 1800

```
###########################################
Alias /discovery /usr/share/discovery/
<LocationMatch ^/discovery/(.*\.php(/.*)?)$>
	ProxyPassMatch fcgi://127.0.0.1:9042/usr/share/discovery/$1 timeout=1800
</LocationMatch>
ProxyTimeout 1800
```
Merci encore pour le module.
Bonne journée.
-pixelabs

**Comment by romnvll** [comment]
Merci pour ton commentaire .
je vais modifier la documentation .
Tu es sur quelle distribution ?

**Comment by aSysadminStory** [comment]
ISO Centreon open source.

**Comment by romnvll** [comment]
Et le timeout 300 n'est pas suffisant ?

**Comment by aSysadminStory** [comment]
Non, j'ai essayé à plusieurs reprise, ça n'a pas fonctionné.
J'ai augmenté uniquement **ProxyTimeout 1800** puis **3600**, toujours le même problème.
C'est après avoir ajouté  **timeout=1800** et après pas mal de minutes (grosse infra), il a affiché une bonne liste de host.

**Comment by romnvll** [comment]
tu l'as fait sur un /24 ?

**Comment by aSysadminStory** [comment]
Nope, je suis en /16 et /10
Je n'ai pas encore tout fait. 
Si je rencontre d'autres problèmes, je reviens vers toi.

**Comment by romnvll** [comment]
ha oui !! /16, et /10 !!! ça à du mettre du temps !!.
Merci pour ton retour 👍
