### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: implode()

### ISSUE THREAD

**Issue by Arawn777** [romnvll/Open-Centreon-Discovery#7]
Hello! 

Je viens de réinstaller OCD sur un Centreon 21.10 tout frais (sous rocky 8.5) pour reprendre mes tests en labo, étrangement le scan en background ne fonctionne plus...

J'ai lancé la commande à la mano et j'obtiens ce message:

[root@localhost discovery]# /usr/bin/php -q backGroundScan.php 

PHP Fatal error:  Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /usr/share/discovery/backGroundScan.php:56
Stack trace:
#0 /usr/share/discovery/backGroundScan.php(56): implode()
#1 {main}
  thrown in /usr/share/discovery/backGroundScan.php on line 56

Fatal error: Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /usr/share/discovery/backGroundScan.php:56
Stack trace:
#0 /usr/share/discovery/backGroundScan.php(56): implode()
#1 {main}
  thrown in /usr/share/discovery/backGroundScan.php on line 56

**Comment by romnvll** [comment]
Salut @Arawn777  !
C'est curieux,
je n'arrive pas a reproduire l'erreur .
et le $pieces, je ne vois pas d'où il vient. Tu n'as rien modifié ? tu peux me faire voir ton fichier de config ?

**Comment by Arawn777** [comment]
Je n'ai rien modifié du tout, je venais juste de réinstaller un rocky linux, mis centreon 21.10 dessus et OCD dans la foulée, tout est tout neuf.
le config.php
![image](https://user-images.githubusercontent.com/94179123/144862271-b77e549b-f8c0-4f6e-ade6-bf035d301584.png)

le backGroundScan.php
![image](https://user-images.githubusercontent.com/94179123/144862751-278832fb-9c1b-4233-a383-cd0593315a65.png)
![image](https://user-images.githubusercontent.com/94179123/144862879-c47906b6-3bb8-4d8c-bc81-a641cc827991.png)

**Comment by Arawn777** [comment]
Et bien entendu aucune trace du fameux $pieces nulle part 

![image](https://user-images.githubusercontent.com/94179123/144863441-d3a1a0c0-c49a-45ca-803c-e1751d4665b8.png)

**Comment by romnvll** [comment]
Est ce que je pourrais prendre la main sur ta machine pour essayer d'y voir plus clair ?

**Comment by romnvll** [comment]
je pense avoir trouvé le bug !
est ce que tu peux faire un git pull stp ?

**Comment by Arawn777** [comment]
Malheureusement te donner les accès ne va pas être possible, mes machines sont hébergées sur le proxmox de ma boite...

Par contre je viens de retester avec ton correctif ça marche nickel , ça remonte parfaitement. Super taf 👍

**Comment by romnvll** [comment]
Merci pour ta réponse.
Et merci beaucoup pour ton aide !
