### ISSUE TITLE
Automatic Discover & Apply

### ISSUE THREAD

**Issue by Spleeff** [romnvll/Open-Centreon-Discovery#8]
Bonjour,

Merci pour votre fantastique développement qui facilite grandement la vie pour les infrastructures de plusieurs centaines d'équipement !
Serait-il possible de m'indiquer s'il est possible d'automatiser également le process d'ajout des hôtes ?
L'idée serait de scanner des plages précises à intervalle régulier pour détecter de nouveaux hôtes, de les ajouter automatiquement dans Centreon et de redémarrer automatiquement le poller sans action humaine ?

Merci de votre aide/conseil

**Comment by romnvll** [comment]
Merci pour votre message!
Ça fait toujours plaisir de savoir que le code que j'ai écrit peut servir à
d'autres personnes !
Juste pour ma culture perso, comment avez-vous connu ce projet ?
Pour revenir à votre demande, oui ça serait envisageable d'intégrer cette
fonctionnalité.

Mais comment voyez-vous le truc ?

Quel template utilise-t-on si on trouve une machine ?

**Comment by Spleeff** [comment]
Via Kermith ;)
Je viens de Nagios et je cherchais une alternative entre Centreon et Zabbix.
Centreon est beaucoup plus simple avec mes habitudes de Nagios mais Zabbix possédait un mode Autodiscover alléchant.
OCD a comblé ce manque !
Naïvement, j'imaginais quelque chose à base de template déjà ajouté dans autoTemplate.js et que si la machine scannée matche avec un template qui n'est pas Unknow, on peut ajouter les hôtes, appliquer la configuration, redémarrer le poller.
On pouvait également imaginer un critère supplémentaire de type range IP pour éviter des redémarrages intempestifs .

Qu'en pensez vous ? Dispo pour en parler via Teams également.

Merci de votre aide !

**Comment by romnvll** [comment]
Ha ce kermith!!!
Moi aussi je trouvais que chez centreon ça manquait un mode auto
discovery...

Ok je vois bien ce que tu veux dire.

Si ça se fait dans le fichier de configuration, ça pourrait aller ?
Genre on dit que pour ce range d'ip de scan back ground, j'autorise l'auto
import et le redémarrage du poller?

Tu es sur quelle version de centreon ?

Merci en tout cas pour cette nouvelle idée :)

**Comment by Spleeff** [comment]
Parfait pour le fichier de configuration !
On pourrait imaginer que ça soit effectif pour plusieurs range IP ? Pour la version, je te redis ça demain, j’aurais tendance à dire 21.04 mais sans certitude ..

**Comment by Spleeff** [comment]
Bonjour,
Je confirme 21.04.10 sous RHEL 8 !

**Comment by romnvll** [comment]
Salut,
En ce qui concerne le poller...
Est-ce que ça veut dire que toutes les machines d'un réseau sont consultés
par le même poller ?

**Comment by Spleeff** [comment]
Salut,
Pour ma part, oui je n’ai qu’un seul poller (Master) qui collecte les données de tous les sites distants. Mais je ne pense pas être un bon élève ;)

**Comment by romnvll** [comment]
J'ai fait des modifications dans OCD .
peux tu faire un git pull, et regarder dans ce fichier :
https://github.com/romnvll/Open-Centreon-Discovery/blob/master/config.php.example

j'ai ajouté deux variables a renseigner
 "autoAdd" =>"true",
 "poller" => "Central",

AutoAdd specifie si tu veux ajouter automatiquement pour ce réseau
et tu dois renseigner le poller qui doit être appliqué pour ces machines trouvées.

j'ai fait quelques tests, et il semblerait que ca fonctionne, mais je n'ai pas pu essayé tous les cas de figure ( genre l'autotemplate pour les machines inconnues ).

ce fichier contient le mappage pour les machines qui ne serait pas reconnu par l'autotemplate .
https://github.com/romnvll/Open-Centreon-Discovery/blob/master/backGroundAdd.php

tiens moi au informé !

**Comment by Spleeff** [comment]
Salut,
Je teste ça dans la soirée et je te tiens au courant !
J’ai même une autre idée à te soumettre .. ;)

**Comment by romnvll** [comment]
Oui je suis preneur !

**Comment by Spleeff** [comment]
Salut, désolé du délai j’ai tenté de me débrouiller par moi même mais je ne parviens pas faire fonctionner OCD. 
Le poller semble être redémarré automatique (champ mise à jour dans Centreon) mais pour autant je n’ai pas d’hôtes ajoutés dans Centreon.
J’ai modifié le fichier config.php ainsi que backGroundAdd.php et autoTemplate.js .. :(

**Comment by romnvll** [comment]
Hello,
on peut se faire un teams ?

**Comment by Spleeff** [comment]
Quand tu veux ;)

**Comment by romnvll** [comment]
https://teams.microsoft.com/l/meetup-join/19%3ameeting_MzI5Njg5ZGUtYzE0Ny00YzgzLWIwYmUtYWU4YTExMjJkYjMw%40thread.v2/0?context=%7b%22Tid%22%3a%22371cb156-9558-4286-a3cd-3059699b890c%22%2c%22Oid%22%3a%22ee0488a3-9da2-4c46-a1fd-e9e0614d0c6e%22%7d

**Comment by romnvll** [comment]
La fonctionnalité est en place :)
